# Just for if using pnpm ; prefer bun install
packages:
  - 'trees/*'
  - '!trees/prismarine-viewer/**'
  - '!trees/prismarine-web-client/**'
  - '!trees/mineflayer-pvp/**'
  - '!trees/prismarine-gameplay/**'
  - '!trees/prismarine-provider-raw/**'
  - '!trees/prismarine-packet-dumper/**'
  - '!trees/minecraft-wiki-extractor/**'
  - '!trees/node-minecraft-extractor/**'